### ISSUE TITLE
Not able to load annotations after viame >= 0.20

### ISSUE THREAD

**Issue by ltetrel** [Kitware/dive#1397]
**Describe the bug**

Loading annotation is not working correctly after 0.20.
It works when loading dataset < `0.20`, then open `>= 0.20` and load from `Recent` section.
```
Error occurred in handler for 'finalize-import': Error: Images were provided in an unexpected order and dataset contains multi-frame tracks.
    at /opt/viame_0.20.3/dive/resources/app.asar/background.js:2:1591647
    at internal/streams/pipeline.js:99:7
    at internal/util.js:392:14
    at o.<anonymous> (internal/streams/pipeline.js:35:5)
    at o.<anonymous> (internal/util.js:392:14)
    at onfinish (internal/streams/end-of-stream.js:56:29)
    at o.emit (events.js:327:22)
    at finishMaybe (_stream_writable.js:639:14)
    at endWritable (_stream_writable.js:656:3)
    at o.Writable.end (_stream_writable.js:595:5)
```

![image](https://github.com/Kitware/dive/assets/37963074/2faed4bf-86cd-4bdd-a7f8-955250887d4e)

**To Reproduce**
1. Download release Linux Full Desktop Binaries v0.20.3 from [there](https://github.com/VIAME/VIAME#installations).
2. Launch dive with launch_dive_interface.sh.
3. Try to import a new image sequence with annotation viame csv format

**Related data**
[annotations_subsample.csv](https://github.com/Kitware/dive/files/13778222/annotations_subsample.csv)

**Expected behavior**
Shoud correctly load after > `0.20`

**Desktop (please complete the following information):**
 - Linux - ubuntu 20.04.6 LTS

**Comment by BryonLewis** [comment]
When loading the annotations, are the only images in the image-sequence loading into the following:
frame000787.png
frame000788.png
frame000789.png
frame000790.png

Are there extra images in the dataset that aren't accounted for which may make the frame order off?

I'm linking this PR for my own reference into what could be causing this problem:  #1344

**Comment by ltetrel** [comment]
In the annotation file, there are some frames that does not include any annotations if that is your question.
Will ping you when the data upload is done.

**Comment by BryonLewis** [comment]
I downloaded and tested with the latest version. Looks like I already fixed this months ago but didn't cut a release (other work was priority):
https://github.com/Kitware/dive/commit/8bcdfdd708b96ea24cad9554dbffd23ae2a6ea31
I could replicate the issue on the default 1.9.4 release.  I just completely forgot about doing this fix at the time.

**Comment by BryonLewis** [comment]
Should hopefully be closed in #1400
