### ISSUE TITLE
[BUG] Logs can fill up mongo

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#809]
**Describe the bug**

Logging in celery can fill up a mongo record and stall the job.

**Comment by subdavis** [comment]
My attempt to fix this failed and needs more investigation.

It seems from the trace that the monkey patch is not getting patched in prod for some reason.

```
1-07-08 09:31:13,671: ERROR/ForkPoolWorker-1] Signal handler <function gw_task_failure at 0x7ff224fb9320> raised: HTTPError('500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573')
Traceback (most recent call last):
  File "/home/worker/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/task.py", line 153, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/home/worker/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/viame_girder/dive_tasks/tasks.py", line 294, in run_pipeline
    process, self, context, manager, process_err_file, cleanup=cleanup
  File "/home/viame_girder/dive_tasks/utils.py", line 73, in stream_subprocess
    manager.write(line_str)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 262, in write
    self._flush()
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 240, in _flush
    req.raise_for_status()
  File "/home/worker/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/worker/venv/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/app.py", line 186, in gw_task_failure
    sender.job_manager.write(msg)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 262, in write
    self._flush()
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 240, in _flush
    req.raise_for_status()
  File "/home/worker/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573
[2021-07-08 09:31:13,673: ERROR/ForkPoolWorker-1] Task dive_tasks.tasks.run_pipeline[613badd2-63c3-414e-b150-d5ca2c6d9f6c] raised unexpected: HTTPError('500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573')
Traceback (most recent call last):
  File "/home/worker/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/task.py", line 153, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/home/worker/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/viame_girder/dive_tasks/tasks.py", line 294, in run_pipeline
    process, self, context, manager, process_err_file, cleanup=cleanup
  File "/home/viame_girder/dive_tasks/utils.py", line 73, in stream_subprocess
    manager.write(line_str)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 262, in write
    self._flush()
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 240, in _flush
    req.raise_for_status()
  File "/home/worker/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573
[2021-07-08 09:31:13,769: ERROR/ForkPoolWorker-1] Signal handler <function gw_task_postrun at 0x7ff224fb9440> raised: HTTPError('500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573')
Traceback (most recent call last):
  File "/home/worker/venv/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/app.py", line 198, in gw_task_postrun
    task.job_manager._flush()
  File "/home/worker/venv/lib/python3.7/site-packages/girder_worker/utils.py", line 240, in _flush
    req.raise_for_status()
  File "/home/worker/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://viame.kitware.com/api/v1/job/60e67a97bc86640ffc79d573

```
